[tool.poetry]
name = "caw"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = ">=3.6"

[tool.poetry.dev-dependencies]
ipython = "^7.15.0"
black = "^19.10b0"
flake8 = "^3.8.2"
flake8-black = "^0.2.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
