name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install poetry
        poetry install -E rss
    - name: Check requirements.txt is up to date
      run: |
        poetry export -E rss -f requirements.txt --without-hashes -o requirements.txt
        git diff --exit-code requirements.txt
    - name: Lint with flake8
      run: |
        poetry run flake8
    - name: Test with pytest
      run: |
        poetry run python -m pytest
    - name: Check with mypy
      run: |
        poetry run mypy -p caw --strict
